import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { awards, contactInfo, education, profile, skills } from '../src/data/profile.ts';
import { projects } from '../src/data/projects.ts';

const scriptPath = fileURLToPath(import.meta.url);
const scriptDir = path.dirname(scriptPath);
const repoRoot = path.resolve(scriptDir, '..');
const generatedDir = path.join(repoRoot, 'cv', 'generated');

function normalizeText(value) {
  return String(value ?? '').trim().replace(/\s+/g, ' ');
}

function escapeLatex(value) {
  return normalizeText(value)
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/([{}#$%&_])/g, '\\$1')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');
}

function command(name, value) {
  return `\\newcommand{\\${name}}{${escapeLatex(value)}}`;
}

function formatCvAffiliation(value) {
  return normalizeText(value).split('/')[0].trim();
}

function formatLinkLabel(url) {
  try {
    const parsed = new URL(url);
    return parsed.host.replace(/^www\./, '') + parsed.pathname.replace(/\/$/, '');
  } catch {
    return url.replace(/^https?:\/\//, '').replace(/\/$/, '');
  }
}

function renderLinkList(links) {
  if (!links) {
    return '';
  }

  const parts = [];

  if (links.paper) {
    parts.push(`Paper: \\href{${links.paper}}{${escapeLatex(formatLinkLabel(links.paper))}}`);
  }

  if (links.code) {
    parts.push(`Code: \\href{${links.code}}{${escapeLatex(formatLinkLabel(links.code))}}`);
  }

  if (links.demo) {
    parts.push(`Demo: \\href{${links.demo}}{${escapeLatex(formatLinkLabel(links.demo))}}`);
  }

  return parts.join(' \\textbar{} ');
}

function renderEducationSection() {
  const lines = ['\\section{Education}'];

  education.forEach((item, index) => {
    lines.push(
      `\\cventry{${escapeLatex(item.degree)}}{${escapeLatex(item.period)}}{${escapeLatex(item.institution)}}`
    );

    const detailItems = [];

    if (item.details) {
      detailItems.push(`  \\item ${escapeLatex(item.details)}`);
    }

    if (index === 0) {
      if (detailItems.length > 0) {
        lines.push('\\begin{itemize}');
        lines.push(...detailItems);
        lines.push('  \\ifstrempty{\\EducationExtras}{}{\\EducationExtras}');
        lines.push('\\end{itemize}');
      } else {
        lines.push('\\ifstrempty{\\EducationExtras}{}{%' );
        lines.push('\\begin{itemize}');
        lines.push('  \\EducationExtras');
        lines.push('\\end{itemize}');
        lines.push('}');
      }
    } else if (detailItems.length > 0) {
      lines.push('\\begin{itemize}');
      lines.push(...detailItems);
      lines.push('\\end{itemize}');
    }
  });

  return lines.join('\n');
}

function renderProjectsSection() {
  const lines = ['\\section{Selected Projects}'];

  projects.forEach((project) => {
    lines.push(
      `\\cvprojectheading{${escapeLatex(project.name)}}{${escapeLatex(project.period)}}{${escapeLatex(project.technologies.join(', '))}}`
    );
    lines.push('\\begin{itemize}');
    lines.push(`  \\item ${escapeLatex(project.summary)}`);
    lines.push(`  \\item ${escapeLatex(project.contribution)}`);

    const linkLine = renderLinkList(project.links);
    if (linkLine) {
      lines.push(`  \\item ${linkLine}`);
    }

    lines.push('\\end{itemize}');
  });

  return lines.join('\n');
}

function renderSkillsSection() {
  return [
    '\\section{Skills}',
    `\\textbf{Technical:} ${escapeLatex(skills.join(', '))}`,
  ].join('\n');
}

function renderAwardsSection() {
  const lines = ['\\section{Honors \\& Activities}', '\\begin{itemize}'];

  awards.forEach((award) => {
    const title = `\\textbf{${escapeLatex(award.title)}}`;
    const period = award.period ? ` (\\textit{${escapeLatex(award.period)}})` : '';
    const description = award.description ? `: ${escapeLatex(award.description)}` : '';

    lines.push(`  \\item ${title}${period}${description}`);
  });

  lines.push('\\end{itemize}');
  return lines.join('\n');
}

function renderBody() {
  return [
    '% Auto-generated by scripts/generate-cv.mjs. Do not edit by hand.',
    '\\section{Summary}',
    escapeLatex(profile.bio),
    '',
    renderEducationSection(),
    '',
    renderAwardsSection(),
    '',
    renderProjectsSection(),
    '',
    renderSkillsSection(),
    '',
  ].join('\n');
}

function renderHeader() {
  return [
    '% Auto-generated by scripts/generate-cv.mjs. Do not edit by hand.',
    command('ProfileName', profile.displayName || profile.name || contactInfo.name || ''),
    command('ProfileTitle', profile.title || ''),
    command('ProfileAffiliation', formatCvAffiliation(profile.affiliation || '')),
    command('ProfileLocation', ''),
    '',
  ].join('\n');
}

export function generateCv() {
  mkdirSync(generatedDir, { recursive: true });

  const headerPath = path.join(generatedDir, 'header.tex');
  const bodyPath = path.join(generatedDir, 'body.tex');

  writeFileSync(headerPath, renderHeader());
  writeFileSync(bodyPath, renderBody());

  return { headerPath, bodyPath };
}

const isDirectRun = process.argv[1] && path.resolve(process.argv[1]) === scriptPath;

if (isDirectRun) {
  const { headerPath, bodyPath } = generateCv();
  console.log(`Generated ${path.relative(repoRoot, headerPath)}`);
  console.log(`Generated ${path.relative(repoRoot, bodyPath)}`);
}
